name: Run the Archiverepo

on:
  push:
     branches:
       - main
  pull_request:
      

env:
  CURRENT_PR_REPO: "${{ github.repository }}"
  GIT_TOKEN: "${{ github.token }}"
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository source code
      uses: actions/checkout@v2
    - run: sudo apt-get update -y
    - run: sudo apt install -y jq
    - run: jq --version
    - run: chmod +x ./transfer_repo.sh
    - run: PR_number=${GITHUB_REF#refs/pull/}
    - run: ./transfer_repo.sh ${{ env.GIT_TOKEN }} ${{ env.CURRENT_PR_REPO }} ${{ PR_number }}
      shell: bash
