name: Run the Archiverepo

on:
  push:
    branches:
      - main

jobs:
  install-nginx:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Archive the repo
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == "true"
        env:
         CURRENT_PR_REPO: ${{ github.repository }}
         PR_NUMBER: ${{ github.event.number }}
         GA_TOKEN: ${{ github.token }}
         shell: bash
         run: |
           sudo apt install -y jq
           echo "jq --version"
           chmod +x ./transfer_repo.sh
           ./transfer_repo.sh ${{ env.GA_TOKEN }} ${{ env.CURRENT_PR_REPO }} ${{ env.PR_NUMBER }}


