name: Run the Archiverepo

on:
  push:
    branches:
      - main
  pull_request:

env:
  CURRENT_PR_REPO: "${{ github.repository }}"
  GIT_TOKEN: "${{ github.token }}"
  GIT_PR : "${{ github.event.pull_request.number }}"
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository source code
      uses: actions/checkout@v2
    - run: sudo apt-get update -y
    - run: sudo apt install -y jq
    - run: jq --version
    - run: echo "PULL_NUMBER=$(echo "$GITHUB_REF" | awk -F / '{print $2}')" >> $GITHUB_ENV
    - run: chmod +x ./transfer_repo.sh
    - run: ./transfer_repo.sh ${{ env.GIT_TOKEN }} ${{ env.CURRENT_PR_REPO }} ${{ env.GIT_PR }}
      shell: bash
