name: Run the Archiverepo

on:
  push:
    branches:
      - main
  pull_request:

env:
  CURRENT_PR_REPO: "${{ github.repository }}"
  PR_NUMBER: "${{ github.event.pull_request.number }}"
  GA_TOKEN: "${{ github.token }}"
  

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout the repository source code
      uses: actions/checkout@v2
    - run: sudo apt-get update -y
    - run: sudo apt install -y jq
    - run: echo "jq --version"
    - run: chmod +x ./transfer_repo.sh
    - run: ./transfer_repo.sh ${{ env.GA_TOKEN }} ${{ env.CURRENT_PR_REPO }} ${{ env.PR_NUMBER }}
      shell: bash
