name: installation of nginx 



on:
  workflow_dispatch:
    inputs:
      triggerworkflow:
        description: 'installing the software'
        required: true
        default: "" 


jobs:
  check-nginx-service:
    runs-on: ubuntu-latest

    steps:
      - name: printing the statement 
        run: |
           echo "Starting the process :${{ github.event.inputs.triggerworkflow }}"

  install-nginx:
    runs-on: [self-hosted,Linux,script-Execution]

    steps:
      - name: setup nginx
        run: |
          sudo apt-get update -y
          sudo apt-get install -y nginx

